services:
  - type: web
    name: mandf-kitchen
    runtime: python
    buildCommand: |
      npm ci
      npm run build
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 3
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: NODE_VERSION
        value: 20.12.2
    staticPublishPath: dist
