services:
  - type: web
    name: mandf-kitchen
    runtime: python
    buildCommand: npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION
        value: 18
